sudo: required
services:
  - docker

language: go

go:
- 1.9

env:
  global:
    - secure: "e7IjyptwfaNmHUYAwTZbLjup0FVD6wVOQIggLSOcqYyrbSYKepVJdbvOUfWqdZ3tUWtpHb5H/2a8RkizXHH3mBi4K5/9wlByTGmiKKA05dYbDod3KpiLbPnHK9UjRQydD6wpYJcK0/yguXmFDqYoRIFwmxeqNJ78OydIo7BOxGY=" 
    - secure: "LEmUhd0lO5BPox3+IdBw/u45Z3TtY0arkef6v7q27qcEs3a2p+SuVVElHx4UcU8/AhN3D9jlskB0UZIgZRMfB3xaPCBVvjHh8UwQ13WqrR7524HuU8kin/4vLDdoIEvs2hQaj58slzmdyddKG2dkgCwkpK/J1DBfKHttbYE+ias=" 
    - secure: "MO3eA15Jp2CkN0SiSI5Oo32wioCcVbaWwpxBCgQrkIyV85yakPzhoWlQWvh90QXEU9bBDKlQiTOXfo11G0as7byU8typa5UI7uLG1sGD9l2bBZbFuqorMrvHl5PeOzfjAQuUnn2KNP5RccuaCn+n65ZImhj8oTFrYGmb1VTdgg0=" 

before_install:
install:
- go get github.com/tools/godep
- go get github.com/clipperhouse/{linkedlist,set,slice,stringer,typewriter}
- go get -t github.com/yinqiwen/gsnova/remote/server github.com/yinqiwen/gsnova/local/client
script:
- cd remote/server && godep save && tar cf ../../tmp-deploy.tar * .godir && cd ../.. && tar uf tmp-deploy.tar server.json && bzip2 tmp-deploy.tar && mv tmp-deploy.tar.bz2 gsnova-paas-deploy-with-dependencies-${TRAVIS_TAG}.tar.bz2
- export CGO_ENABLED=0
- GOOS=windows GOARCH=386 go build -o gsnova_client.exe github.com/yinqiwen/gsnova/local/client
- tar cjf gsnova_client_windows_386-${TRAVIS_TAG}.tar.bz2 client.json hosts.json cnipset.txt gsnova_client.exe
- GOOS=windows GOARCH=amd64 go build -o gsnova_client.exe github.com/yinqiwen/gsnova/local/client
- tar cjf gsnova_client_windows_amd64-${TRAVIS_TAG}.tar.bz2 client.json hosts.json cnipset.txt gsnova_client.exe
- GOOS=linux GOARCH=386 go build -o gsnova_client github.com/yinqiwen/gsnova/local/client
- tar cjf gsnova_client_linux_386-${TRAVIS_TAG}.tar.bz2 client.json hosts.json cnipset.txt gsnova_client
- GOOS=linux GOARCH=amd64 go build -o gsnova_client github.com/yinqiwen/gsnova/local/client
- tar cjf gsnova_client_linux_amd64-${TRAVIS_TAG}.tar.bz2 client.json hosts.json cnipset.txt gsnova_client
- GOOS=linux GOARCH=arm GOARM=5 go build -o gsnova_client github.com/yinqiwen/gsnova/local/client
- tar cjf gsnova_client_linux_armv5-${TRAVIS_TAG}.tar.bz2 client.json hosts.json cnipset.txt gsnova_client
- GOOS=linux GOARCH=arm GOARM=6 go build -o gsnova_client github.com/yinqiwen/gsnova/local/client
- tar cjf gsnova_client_linux_armv6-${TRAVIS_TAG}.tar.bz2 client.json hosts.json cnipset.txt gsnova_client
- GOOS=linux GOARCH=arm GOARM=7 go build -o gsnova_client github.com/yinqiwen/gsnova/local/client
- tar cjf gsnova_client_linux_armv7-${TRAVIS_TAG}.tar.bz2 client.json hosts.json cnipset.txt gsnova_client
- GOOS=linux GOARCH=arm64  go build -o gsnova_client github.com/yinqiwen/gsnova/local/client
- tar cjf gsnova_client_linux_arm64-${TRAVIS_TAG}.tar.bz2 client.json hosts.json cnipset.txt gsnova_client
- GOOS=linux GOARCH=mipsle  go build -o gsnova_client github.com/yinqiwen/gsnova/local/client
- tar cjf gsnova_client_linux_mipsle-${TRAVIS_TAG}.tar.bz2 client.json hosts.json cnipset.txt gsnova_client
- GOOS=linux GOARCH=mips  go build -o gsnova_client github.com/yinqiwen/gsnova/local/client
- tar cjf gsnova_client_linux_mips-${TRAVIS_TAG}.tar.bz2 client.json hosts.json cnipset.txt gsnova_client
- GOOS=darwin GOARCH=amd64 go build -o gsnova_client github.com/yinqiwen/gsnova/local/client
- tar cjf gsnova_client_macos_amd64-${TRAVIS_TAG}.tar.bz2 client.json hosts.json cnipset.txt gsnova_client
- GOOS=linux GOARCH=386 go build -o gsnova_server github.com/yinqiwen/gsnova/remote/server
- tar cjf gsnova_server_linux_386-${TRAVIS_TAG}.tar.bz2 server.json gsnova_server
- GOOS=linux GOARCH=amd64 go build -o gsnova_server github.com/yinqiwen/gsnova/remote/server
- tar cjf gsnova_server_linux_amd64-${TRAVIS_TAG}.tar.bz2 server.json gsnova_server



deploy:
  provider: releases
  api_key:
    secure: YngDT2JlydCG+qb8Ww9wBFyWiLRQJczybNLeoFKluBXKoh1Vu+TZeReMK+rRUjOqOmYV8sNtOnEVSg4+ICeYDNp9fRRwcNKTkp0H+8pH0OynxdH2faCjx1H5U0WQuWqMLQoMSHZ90I0tL40kEJOChLY6WGvwY47YBqi/dsvmTfg=
  file: 
    - "gsnova-paas-deploy-with-dependencies-${TRAVIS_TAG}.tar.bz2"
    - "gsnova_client_windows_386-${TRAVIS_TAG}.tar.bz2"
    - "gsnova_client_windows_amd64-${TRAVIS_TAG}.tar.bz2"
    - "gsnova_client_linux_386-${TRAVIS_TAG}.tar.bz2"
    - "gsnova_client_linux_amd64-${TRAVIS_TAG}.tar.bz2"
    - "gsnova_client_linux_armv5-${TRAVIS_TAG}.tar.bz2"
    - "gsnova_client_linux_armv6-${TRAVIS_TAG}.tar.bz2"
    - "gsnova_client_linux_armv7-${TRAVIS_TAG}.tar.bz2"
    - "gsnova_client_linux_arm64-${TRAVIS_TAG}.tar.bz2"
    - "gsnova_client_linux_mips-${TRAVIS_TAG}.tar.bz2"
    - "gsnova_client_linux_mipsle-${TRAVIS_TAG}.tar.bz2"
    - "gsnova_client_macos_amd64-${TRAVIS_TAG}.tar.bz2"
    - "gsnova_server_linux_amd64-${TRAVIS_TAG}.tar.bz2"
    - "gsnova_server_linux_386-${TRAVIS_TAG}.tar.bz2"
  skip_cleanup: true
  on:
    tags: true
    repo: yinqiwen/gsnova

after_deploy:
  - curl -O -L https://github.com/grammarly/rocker/releases/download/1.3.1/rocker-1.3.1_linux_amd64.tar.gz
  - tar zxf rocker-0.2.2_linux_amd64.tar.gz
  - ./rocker build -f Docker/server/Rockerfile --auth $DOCKER_USER:$DOCKER_PASS --push -var Version=$TRAVIS_TAG 
